config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: 'welcome#home'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboards#index'

  get '/workouts', to: 'workouts#index'
  get '/community', to: 'community#index'
  get '/advice', to: 'advice#index'

  resources :users, only: [:new, :create, :edit, :update]
  resources :workouts do
    resources :exercises do
      resources :setlists
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
  has_many :setlists, dependent: :destroy
end

app/models/setlist.rb
class Setlist < ApplicationRecord
  belongs_to :exercise
end

app/models/user.rb
class User < ApplicationRecord
  has_many :workouts, dependent: :destroy
  has_many :exercises, through: :workouts

  has_secure_password

  validates_presence_of :first_name
  validates :email, presence: true, uniqueness: true
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :exercises, dependent: :destroy
end

app/controllers/admins/omniauth_callbacks_controller.rb
class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    admin = Admin.from_google(from_google_params)

    if admin.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect admin, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_admin_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_admin_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private


  def from_google_params
    @from_google_params ||= {
      uid: auth.uid,
      email: auth.info.email,
      full_name: auth.info.name,
      avatar_url: auth.info.image
    }
  end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  def after_sign_out_path_for(_resource_or_scope)
    new_admin_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
end

app/controllers/advice_controller.rb
class AdviceController < ApplicationController
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  #before_action :authenticate_admin!
  allow_browser versions: :modern
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :authenticate_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user
    @current_user
  end
end

app/controllers/community_controller.rb
class CommunityController < ApplicationController
  def index
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
  
  def show
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def create
    @workout = Workout.find(params[:workout_id])
    @exercise = @workout.exercises.create(exercise_params)
    redirect_to workout_path(@workout)
  end

  def destroy
    @workout = Workout.find(params[:workout_id])
    @exercise = @workout.exercises.find(params[:id])
    @exercise.destroy
    redirect_to workout_path(@workout)
  end

  private
    def exercise_params
      params.require(:exercise).permit(:exercise_name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email].downcase)

    if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to dashboard_path, notice: "Welcome back!"
    else
      flash.now.alert = "Incorrect email or password, please try again."
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: "Successfully logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    @user.email.downcase!

    if @user.save
      flash[:notice] = "Welcome to Personal Trainer #{@user.first_name}"
      session[:user_id] = @user.id

      redirect_to :dashboard
    else
      flash.now.alert = "Please try again."
      render :new
    end
  end

  def edit
    if current_user && (current_user.id == params[:id].to_i)
      @user = User.find(params[:id])
    else
      render file: '/public/404'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to dashboard_path
  end

  def dashboard
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    if current_user && current_user.id
      @workouts = Workout.where(user_id: current_user.id)
    else
      redirect_to root_path
    end
  end

  def show
    @workout = Workout.find(params[:id])
    if @workout.user_id == current_user.id
      @workout
    else
      redirect_to dashboard_path
    end
  end

  def new
    @workout = Workout.new
  end

  def create
    # @user = current_user
    # @workout = @user.workouts.create(workout_parms)
    @workout = Workout.new(workout_params)
    @workout.user_id = current_user.id

    if @workout.save
      redirect_to @workout
    else
      render :new
    end
  end

  def edit
    @workout = Workout.find(params[:id])
    @workout if @workout.user_id == current_user.id
  end

  def update
    @workout = Workout.find(params[:id])

    if @workout.update(workout_params)
      redirect_to @workout
    else
      render :edit
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy if @workout.user_id == current_user.id

    redirect_to dashboard_path
  end

  private
    def workout_params
      params.require(:workout).permit(:title, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/advice/index.html.erb
<div class="root_view">
  <div class="advice_view center_column">
    <h1>Advice</h1>
    <div class="advice_view-links">
      <a href="https://www.nsca.com/education/articles/">National Strength and Conditioning Assoc.</a><br />
      <a href="https://www.bodybuilding.com/category/training">Bodybuilding.com</a><br />
      <a href="https://www.womenshealthmag.com/">Women's Health Magazine</a><br />
      <a href="https://www.menshealth.com/">Men's Health Magazine</a><br />
      <a href="https://www.cooperinstitute.org/research/">Cooper Institute</a><br />
    </div>
  </div>
</div>

app/views/community/index.html.erb
<div class="root_view">
  <div class="community_view">
    <h1>Community Page</h1>
    <div class="community_view-slideshow_container">
      <div class="mySlides fade">
        <div class="numbertext">1 / 6</div>
          <%= image_tag "user_photos/user_1.jpg", class: "community_image" %>
        <div class="text"></div>
      </div>
      <div class="mySlides fade">
        <div class="numbertext">2 / 6</div>
          <%= image_tag "user_photos/user_2.jpg", class: "community_image-vertical" %>
        <div class="text"></div>
      </div>
      <div class="mySlides fade">
        <div class="numbertext">3 / 6</div>
          <%= image_tag "user_photos/user_3.jpg", class: "community_image" %>
        <div class="text"></div>
      </div>
      <div class="mySlides fade">
        <div class="numbertext">4 / 6</div>
          <%= image_tag "user_photos/user_4.jpg", class: "community_image-vertical" %>
        <div class="text"></div>
      </div>
      <div class="mySlides fade">
        <div class="numbertext">5 / 6</div>
          <%= image_tag "user_photos/user_5.jpg", class: "community_image" %>
        <div class="text"></div>
      </div>
      <div class="mySlides fade">
        <div class="numbertext">6 / 6</div>
          <%= image_tag "user_photos/user_6.jpg", class: "community_image-vertical" %>
        <div class="text"></div>
      </div>
      <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next" onclick="plusSlides(1)">&#10095;</a>
    </div>
    <br>
    <div style="text-align:center">
      <span class="dot" onclick="currentSlide(1)"></span>
      <span class="dot" onclick="currentSlide(2)"></span>
      <span class="dot" onclick="currentSlide(3)"></span>
      <span class="dot" onclick="currentSlide(4)"></span>
      <span class="dot" onclick="currentSlide(5)"></span>
      <span class="dot" onclick="currentSlide(6)"></span>
    </div>
  </div>
</div>

<script>
  var slideIndex = 1;
  showSlides(slideIndex);

  function plusSlides(n) {
    showSlides(slideIndex += n);
  }

  function currentSlide(n) {
    showSlides(slideIndex = n);
  }

  function showSlides(n) {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    if (n > slides.length) {slideIndex = 1}
    if (n < 1) {slideIndex = slides.length}
    for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " active";
  }
</script>

app/views/dashboards/index.html.erb
<div class="root_view">
  <div class="dashboard_view center_column">
    <h1>Dashboard</h1>
  </div>
</div>

app/views/exercises/_exercise.html.erb
<div class="exercise_div">
  <div class="exercise_div-name">
    Exercise:
    <%= exercise.exercise_name %>
  </div>
  <div>
  <%= link_to 'Remove Exercise', [exercise.workout, exercise],
      method: :delete,
      data: { confirm: "Are you sure?" } %>
  </div>
</div>

app/views/exercises/_form.html.erb
<%= form_with model: [ @workout, @workout.exercises.build] do |form|%>
  <div class="form_field">
    <div class="form_label">
      <%= form.label :exercise_name %>
    </div>
    <br />
    <%= form.text_field :exercise_name %>
  </div>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Personal Trainer" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if current_user %>
      <%= render "shared/navigation" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/setlists/_form.html.erb
<%= form_with model: [ @exercise, @exercise.setlists.build ] do |form| %>
  <p>
    <%= form.label :type %><br />
    <%= form.text_field :type %>
  </p>
  <p>
    <%= form.label :weight %><br />
    <%= form.number_field :weight %>
  </p>
  <p>
    <%= form.label :reps %><br />
    <%= form.number_field :reps %>
  </p>

  <p>
    -- or --
  </p>

  <p>
    <%= form.label :duration %><br />
    <%= form.number_field :duration %>
  </p>
<% end %>

app/views/setlists/_setlist.html.erb
<p>
  Reps:
  <%= setlist.reps %>
</p>
<p>
  Weight:
  <%= setlist.weight %>
</p>
<p>
  <%= link_to 'Remove Set', [setlist.exercise, setlist],
      method: :delete,
      data: { confirm: "Are you sure?" } %>
</p>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top" style="">
  <div class="navbar_title">
    <% if current_user %>
      <h1 class="navbar-brand">
        <%= link_to "Personal Trainer", dashboard_path, class: "nav-link" %>
      </h1>
    <% end %>
  </div>
  <div class="navbar_navigation">
    <% unless current_user %>
      <div class="navbar_nav-item">
        <%= link_to "Log In", login_path, class: "nav-link" %>  /
      </div>
    <% end %>

    <div class="navbar_nav-item">
      <%= link_to "Workouts", workouts_path, class: "nav-link" %>  /
    </div>
    <div class="navbar_nav-item">
      <%= link_to "Advice", advice_path, class: "nav-link" %>  /
      /
    </div>
    <div class="navbar_nav-item">
      <%= link_to "Community Photos", community_path, class: "nav-link" %>  /
    </div>
    <% if current_user.present? %>
      <p class="navbar-brand">
        <%= "Logged in as #{current_user.first_name} " %>
      </p>
    <% end %>
    <% if current_user %>
      <div class="navbar_nav-item">
        <%= link_to "Log Out", logout_path, method: "delete", class: "nav-link" %>
      </div>
    <% end %>
  </div>
</nav>

app/views/users/_form.html.erb
<div class="user-form">
  <%= form_for @user do |f| %>
    <div class="form-section">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, autofocus: true, class: "form-control", placeholder: "Enter first name" %>
    </div>
    </br>
    <div class="form-section">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, autofocus: true, class: "form-control", placeholder: "Enter last name" %>
    </div>
    </br>
    <div class="form-section">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
      <small class="form-text text-muted">
          We'll never share your email with anyone else.
      </small>
    </div>
    </br>
    <div class="form-section">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
    </div>
    </br>
    <div class="form-section">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
    </div>
    </br>
    <div class="form-section">
      <%= f.submit 'Submit', class: "btn" %>
    </div>
  <% end %>
</div>

app/views/users/dashboard.html.erb
<h1>Dashboard</h1>

app/views/users/new.html.erb
<div class="root_view">
  <h1>Please provide your info to get started.</h1>
  <%= render partial: 'form' %>  
</div>

app/views/welcome/home.html.erb
<div class="root_view">
  <div class="home_view center_column">
    <h1>Personal Trainer</h1>
    <%= image_tag "frontpage.jpg", class: "home_view-image" %>
    <div class="home_view__buttons-container">
      <!-- <div class="main-view__button">
        <%= link_to "Continue as Guest", root_path %>
      </div> -->
      <div class="main-view__button">
        <%= link_to "Login / Create Account", login_path, class: "home_view-login_button" %>
      </div>
    </div>
  </div>
</div>

app/views/workouts/_form.html.erb
<%= form_with model: workout do |form| %>
  <div>
    <%= form.label :title, class: 'form_label' %><br />
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/workouts/index.html.erb
<div class="root_view">
  <div class="workouts_view center_column">
    <h1>Workouts</h1>

    <ul>
      <% @workouts.each do |workout| %>
        <li>
          <%= link_to workout.title, workout %>
        </li>
      <% end %>
    </ul>

    <%= link_to "New Workout", new_workout_path %>
  </div>
</div>

app/views/workouts/new.html.erb
<div class="root_view">
  <h1>New Workout</h1>

  <%= render "form", workout: @workout %>
</div>

app/views/workouts/show.html.erb
<div class="root_view">
  <h1><%= @workout.title %></h1>

  <div>
    <%= link_to "Edit", edit_workout_path(@workout) %>
    <%= link_to "Delete", workout_path(@workout), method: :delete, data: { confirm: "Are you sure?"} %>
  </div>


  <p>Sets</p>
  <%= render @workout.exercises %>

  <h1>Add an Exercise:</h1>
  <%= render 'exercises/form' %>
</div>